### ISSUE TITLE
return problem with execute method

### ISSUE THREAD

**Issue by mr-m0nst3r** [federicodotta/Brida#30]
Here's the class to inspect:
`public static String encodeEncry(String jsonObject) throws UnsupportedEncodingException {`

Here's the js code:
```javascript
var res = null; // global var to get res
rpc.exports = {
	
	// BE CAREFUL: Do not use uppercase characters in exported function name (automatically converted lowercase by Pyro)
	
	myenc: function (param) {
		Java.perform(function () {
			var endec_class = Java.use("xxx.TransDataEncry");
			//res = "121212"; // got res
			var myinstance = endec_class.$new();
			res = myinstance.encodeEncry("123123123");
		});
		return res;
	},
}
```

Here's the exception from the console:
```
Exception with execute method net.razorvine.pyro.PyroException: [frida.core.RPCException] cannot read property 'then' of null net.razorvine.pyro.serializer.PyroExceptionSerpent.FromSerpentDict(PyroExceptionSerpent.java:32) net.razorvine.pyro.serializer.SerpentSerializer$DictConverter.convert(SerpentSerializer.java:58) net.razorvine.serpent.ObjectifyVisitor.visit(ObjectifyVisitor.java:69) net.razorvine.serpent.ast.DictNode.accept(DictNode.java:8) net.razorvine.serpent.ast.Ast.accept(Ast.java:51) net.razorvine.serpent.ast.Ast.getData(Ast.java:45) net.razorvine.pyro.serializer.SerpentSerializer.deserializeData(SerpentSerializer.java:47) net.razorvine.pyro.PyroProxy.internal_call(PyroProxy.java:272) net.razorvine.pyro.PyroProxy.call(PyroProxy.java:178) burp.BurpExtender.actionPerformed(BurpExtender.java:1385) javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) java.awt.Component.processMouseEvent(Component.java:6533) javax.swing.JComponent.processMouseEvent(JComponent.java:3324) java.awt.Component.processEvent(Component.java:6298) java.awt.Container.processEvent(Container.java:2236) java.awt.Component.dispatchEventImpl(Component.java:4889) java.awt.Container.dispatchEventImpl(Container.java:2294) java.awt.Component.dispatchEvent(Component.java:4711) java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) java.awt.Container.dispatchEventImpl(Container.java:2280) java.awt.Window.dispatchEventImpl(Window.java:2746) java.awt.Component.dispatchEvent(Component.java:4711) java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) java.awt.EventQueue.access$500(EventQueue.java:97) java.awt.EventQueue$3.run(EventQueue.java:709) java.awt.EventQueue$3.run(EventQueue.java:703) java.security.AccessController.doPrivileged(Native Method) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) java.awt.EventQueue$4.run(EventQueue.java:731) java.awt.EventQueue$4.run(EventQueue.java:729) java.security.AccessController.doPrivileged(Native Method) java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) java.awt.EventQueue.dispatchEvent(EventQueue.java:728) java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Thank you!

**Comment by mr-m0nst3r** [comment]
and I tried python stub but also got error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michael/Library/Python/2.7/lib/python/site-packages/Pyro4/core.py", line 185, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/Users/michael/Library/Python/2.7/lib/python/site-packages/Pyro4/core.py", line 467, in _pyroInvoke
    data = serializer.deserializeData(msg.data, compressed=msg.flags & message.FLAGS_COMPRESSED)
  File "/Users/michael/Library/Python/2.7/lib/python/site-packages/Pyro4/util.py", line 171, in deserializeData
    return self.loads(data)
  File "/Users/michael/Library/Python/2.7/lib/python/site-packages/Pyro4/util.py", line 614, in loads
    return self.recreate_classes(serpent.loads(data))
  File "/Users/michael/Library/Python/2.7/lib/python/site-packages/Pyro4/util.py", line 416, in recreate_classes
    return self.dict_to_class(literal)
  File "/Users/michael/Library/Python/2.7/lib/python/site-packages/Pyro4/util.py", line 633, in dict_to_class
    return super(SerpentSerializer, cls).dict_to_class(data)
  File "/Users/michael/Library/Python/2.7/lib/python/site-packages/Pyro4/util.py", line 395, in dict_to_class
    raise errors.SerializeError("unsupported serialized class: " + classname)
Pyro4.errors.SerializeError: unsupported serialized class: frida.core.RPCException

```

Here's the stub:
```python
import Pyro4

uri = 'PYRO:BridaServicePyro@127.0.0.1:9999'
pp = Pyro4.Proxy(uri)
args = []
args.append("Hello World")
ret = pp.callexportfunction('myenc',args)
print ret
pp._pyroRelease()
```

**Comment by mr-m0nst3r** [comment]
My mistake, I hooked a wrong similar class name.
I'm closing it, but can't delete it.
Embarassing.....
